# Generated by Django 2.2.5 on 2019-10-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
