# Generated by Django 2.2.5 on 2019-09-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'menu', 'verbose_name_plural': 'menus'},
        ),
    ]
