# Generated by Django 2.2.5 on 2019-09-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0002_auto_20190915_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
    ]
