# Generated by Django 2.2.5 on 2019-11-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0002_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
