# Generated by Django 2.2.5 on 2019-11-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0003_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(default='card0.jpg', upload_to=''),
        ),
    ]
