# Generated by Django 2.2.5 on 2019-09-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0003_auto_20190915_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('employee', models.ManyToManyField(to='MenuServe.Employee')),
                ('manager', models.ManyToManyField(to='MenuServe.Manager')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ManyToManyField(to='MenuServe.Manager'),
        ),
    ]
