# Generated by Django 2.2.5 on 2019-09-20 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0004_auto_20190919_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MenuServe.Manager'),
        ),
    ]
