# Generated by Django 2.2.5 on 2019-09-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0005_auto_20190920_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MenuServe.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('store', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('status', models.BooleanField()),
                ('menuOrder', models.ManyToManyField(through='MenuServe.MenuOrder', to='MenuServe.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='menuorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MenuServe.Order'),
        ),
    ]
