# Generated by Django 2.2.5 on 2019-09-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0006_auto_20190920_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='menuOrder',
            new_name='menus',
        ),
    ]
