# Generated by Django 2.2.5 on 2019-09-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0007_auto_20190920_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('num', models.IntegerField()),
            ],
        ),
    ]
