# Generated by Django 2.2.5 on 2019-09-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='menuId',
            field=models.IntegerField(default=1),
        ),
    ]
