# Generated by Django 2.2.5 on 2019-09-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuServe', '0009_cart_menuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='menuId',
            field=models.IntegerField(),
        ),
    ]
